# Generated by Django 3.0.6 on 2020-05-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('surname', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='surname')),
                ('email', models.IntegerField(max_length=100, verbose_name='email')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price'),
        ),
    ]
